// src/content/labels.ts
//
// ┌──────────────────────────────────────────────────────────────────────┐
// │  THIS IS THE FILE YOU EDIT TO CHANGE WHAT THINGS ARE CALLED.          │
// └──────────────────────────────────────────────────────────────────────┘
//
// One block per language: a noun for every item kind and every part of the
// building, plus the two words for 'outside' (which is a destination but not a
// room). Room names live on the rooms themselves in rooms.ts. The type makes this table
// TOTAL: add a language to `Locale` or an item to `ItemKind` and this file stops
// compiling until every blank is filled. You can't ship a half-translated house.
//
// Articles are included (el/la, der/die/das) because the gendered article is
// part of learning the noun — a bare "mesa" teaches you less than "la mesa".

import type { LabelTable } from '../core/house/labels';

export const LABELS: LabelTable = {
  en: {
    nouns: {
      diningTable: 'the dining table',
      dishwasher: 'the dishwasher',
      table: 'the table',
      chair: 'the chair',
      sofa: 'the sofa',
      rug: 'the rug',
      bookshelf: 'the bookshelf',
      laptop: 'the laptop',
      tv: 'the television',
      counter: 'the counter',
      oven: 'the oven',
      fridge: 'the fridge',
      toilet: 'the toilet',
      bathtub: 'the bathtub',
      shower: 'the shower',
      sink: 'the sink',
      bed: 'the bed',
      wardrobe: 'the wardrobe',
      nightstand: 'the nightstand',
      door: 'the door',
      frontDoor: 'the front door',
      window: 'the window',
      wall: 'the wall',
      floor: 'the floor',
      ceiling: 'the ceiling',
      roof: 'the roof',
      stairs: 'the stairs',
    },
    months: {
      january: 'January',
      february: 'February',
      march: 'March',
      april: 'April',
      may: 'May',
      june: 'June',
      july: 'July',
      august: 'August',
      september: 'September',
      october: 'October',
      november: 'November',
      december: 'December',
    },
    outside: 'outside',
    goOutside: 'Go outside',
    closeDoor: 'Close the door',
  },
  es: {
    nouns: {
      diningTable: 'la mesa de comedor',
      dishwasher: 'el lavavajillas',
      table: 'la mesa',
      chair: 'la silla',
      sofa: 'el sofá',
      rug: 'la alfombra',
      bookshelf: 'la estantería',
      laptop: 'el portátil',
      tv: 'la televisión',
      counter: 'la encimera',
      // NOT 'la cocina': that is already the KITCHEN two lines of this app away,
      // and teaching one word for two things is exactly what a picture-based
      // vocabulary tool exists to avoid. 'el horno' names the appliance only.
      oven: 'el horno',
      fridge: 'la nevera',
      toilet: 'el inodoro',
      bathtub: 'la bañera',
      shower: 'la ducha',
      sink: 'el lavabo',
      bed: 'la cama',
      wardrobe: 'el armario',
      nightstand: 'la mesita de noche',
      door: 'la puerta',
      frontDoor: 'la puerta principal',
      window: 'la ventana',
      wall: 'la pared',
      floor: 'el suelo',
      ceiling: 'el techo',
      roof: 'el tejado',
      stairs: 'la escalera',
    },
    months: {
      january: 'enero',
      february: 'febrero',
      march: 'marzo',
      april: 'abril',
      may: 'mayo',
      june: 'junio',
      july: 'julio',
      august: 'agosto',
      september: 'septiembre',
      october: 'octubre',
      november: 'noviembre',
      december: 'diciembre',
    },
    outside: 'afuera',
    goOutside: 'Sal afuera',
    closeDoor: 'Cierra la puerta',
  },
  de: {
    nouns: {
      diningTable: 'der Esstisch',
      dishwasher: 'die Spülmaschine',
      table: 'der Tisch',
      chair: 'der Stuhl',
      sofa: 'das Sofa',
      rug: 'der Teppich',
      bookshelf: 'das Bücherregal',
      laptop: 'der Laptop',
      tv: 'der Fernseher',
      counter: 'die Arbeitsplatte',
      oven: 'der Backofen',
      fridge: 'der Kühlschrank',
      toilet: 'die Toilette',
      bathtub: 'die Badewanne',
      shower: 'die Dusche',
      sink: 'das Waschbecken',
      bed: 'das Bett',
      wardrobe: 'der Kleiderschrank',
      nightstand: 'der Nachttisch',
      door: 'die Tür',
      frontDoor: 'die Haustür',
      window: 'das Fenster',
      wall: 'die Wand',
      floor: 'der Boden',
      ceiling: 'die Decke',
      roof: 'das Dach',
      stairs: 'die Treppe',
    },
    months: {
      january: 'Januar',
      february: 'Februar',
      march: 'März',
      april: 'April',
      may: 'Mai',
      june: 'Juni',
      july: 'Juli',
      august: 'August',
      september: 'September',
      october: 'Oktober',
      november: 'November',
      december: 'Dezember',
    },
    outside: 'draußen',
    goOutside: 'Geh nach draußen',
    closeDoor: 'Schließ die Tür',
  },
};